trigger:
  - master

jobs:
- job: Ruby 2.6
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.6.2'

  - script: |
      gem install bundler
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'

  - script: bundle exec rspec --format RspecJunitFormatter --out test_results/test-rspec.xml
    displayName: 'bundle exec rspec'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Ruby tests'

- job: Ruby 2.5
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '2.5.5'

  - script: |
      gem install bundler
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'

  - script: bundle exec rspec --format RspecJunitFormatter --out test_results/test-rspec.xml
    displayName: 'bundle exec rspec'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Ruby tests'
