#!/bin/sh

set -e

echo "===> Bundling..."
script/bootstrap --quiet

if [[ -z "$OCTOKIT_TEST_GITHUB_LOGIN" ]]; then
    echo "Please export OCTOKIT_TEST_GITHUB_LOGIN";
    exit 1;
fi

if [[ -z "$OCTOKIT_TEST_GITHUB_PASSWORD" ]]; then
    echo "Please export OCTOKIT_TEST_GITHUB_PASSWORD";
    exit 1;
fi

if [[ -z "$OCTOKIT_TEST_GITHUB_TOKEN" ]]; then
    echo "Please export OCTOKIT_TEST_GITHUB_TOKEN"
    exit 1;
fi

echo "===> Running specs..."
bundle exec rspec-queue spec
